import { describe, it, expect } from 'vitest';
import { rulesToSieve, sieveToRules } from './sieveGenerator';
import { SieveRule } from '../types/sieve';

// 用戶真實環境嘅 Roundcube 生成腳本（截圖版本，已脫敏）
const ROUND_CUBE_STYLE = `require ["fileinto","imap4flags"];
# rule:[Jobsdb]
if anyof (address :domain :matches "from" "*jobsdb.com", address :domain :matches "from" "*jobsdbmail.com", address :contains "from" "ctgoodjobsbsc.hk", address :contains "from" "ctgoodjobsalert.hk")
{
  setflag "\\\\Seen";
  fileinto "Jobsdb";
  stop;
}

# rule:[facebook]
if address :contains "from" "@facebookmail.com"
{
  fileinto "facebook";
  stop;
}
`;

describe('sieveToRules進階語法', () => {
  it('解析 Roundcube 風格腳本（anyof + address :domain + setflag + 隔行大括號）', () => {
    const rules = sieveToRules(ROUND_CUBE_STYLE);
    expect(rules).not.toBeNull();
    expect(rules!.length).toBe(2);
    expect(rules![0].name).toBe('Jobsdb');
    expect(rules![0].conditionJoin).toBe('anyof');
    expect(rules![0].conditions.length).toBe(4);
    expect(rules![0].conditions[0].test).toBe('address');
    expect(rules![0].conditions[0].part).toBe('domain');
    expect(rules![0].conditions[0].op).toBe('matches');
    expect(rules![0].conditions[0].value).toBe('*jobsdb.com');
    const flags = rules![0].actions.find((a) => a.type === 'setflag');
    expect(flags).toBeTruthy();
    expect(flags!.flag).toBe('\\Seen');
    expect(rules![0].actions.find((a) => a.type === 'fileinto')!.mailbox).toBe('Jobsdb');
  });

  it('規則模式 → sieve → 規則模式 往返穩定', () => {
    const rules = sieveToRules(ROUND_CUBE_STYLE)!;
    const gen = rulesToSieve(rules);
    const again = sieveToRules(gen);
    expect(again).not.toBeNull();
    expect(again!.length).toBe(2);
    expect(again![0].conditions.length).toBe(4);
    // 再生成一次，內容應與上一次一致（冪等）
    expect(rulesToSieve(again!)).toBe(gen);
  });

  it('解析 header :contains / :is、exists、not、fileinto :copy', () => {
    const src = `require ["fileinto","copy"];
# rule:[mixed]
if allof (header :contains "Subject" "A", not header :is "From" "boss@x.com", exists "List-Id")
{
  fileinto :copy "Archive";
}
`;
    const rules = sieveToRules(src);
    expect(rules).not.toBeNull();
    expect(rules![0].conditions.length).toBe(3);
    expect(rules![0].conditions.some((c) => c.negated)).toBe(true);
    expect(rules![0].conditions.some((c) => c.test === 'exists')).toBe(true);
    expect(rules![0].actions[0].copy).toBe(true);
  });

  it('allof 內出現多值 string-list（隱式 anyof）→ 語義不安全，回退原始碼模式', () => {
    const src = `if allof (header :contains "Subject" ["A","B"], exists "X") { fileinto "Y"; }`;
    expect(sieveToRules(src)).toBeNull();
  });

  it('支援大括號同行／獨立行／單行 if', () => {
    const a = sieveToRules(`if header :contains "Subject" "x" { fileinto "Y"; stop; }`);
    const b = sieveToRules(`if header :contains "Subject" "x"\n{\nfileinto "Y";\nstop;\n}`);
    expect(a).not.toBeNull();
    expect(b).not.toBeNull();
    expect(a![0].conditions[0].value).toBe('x');
    expect(b![0].conditions[0].value).toBe('x');
  });

  it('唔支援嘅語法（vacation / variable / envelope）回傳 null 降原始碼模式', () => {
    expect(sieveToRules(`require ["vacation"];\nif true { vacation "gone"; }`)).toBeNull();
    expect(sieveToRules(`if envelope :is "from" "x" { stop; }`)).toBeNull();
    expect(sieveToRules(`if true { set "v" "x"; }`)).toBeNull();
    expect(sieveToRules(`if header :contains "a" "b" { keep; } elsif header :contains "c" "d" { keep; }`)).toBeNull();
  });

  it('生成器自動推斷 require 列表', () => {
    const rules: SieveRule[] = [
      {
        id: 'r1',
        name: 'flag and move',
        enabled: true,
        conditionJoin: 'allof',
        conditions: [
          { id: 'c1', test: 'address', part: 'domain', op: 'contains', negated: false, header: 'from', value: 'spam.example' },
        ],
        actions: [
          { id: 'a1', type: 'setflag', flag: '\\Seen' },
          { id: 'a2', type: 'fileinto', mailbox: 'Junk' },
          { id: 'a3', type: 'stop' },
        ],
      },
    ];
    const out = rulesToSieve(rules);
    expect(out).toContain('require ["fileinto","imap4flags"];');
    expect(out).toContain('address :domain :contains "from" "spam.example"');
    expect(out).toContain('setflag "\\\\Seen";');
    expect(out).toContain('fileinto "Junk";');
    // 已有 stop 就唔會重複加
    expect((out.match(/stop;/g) || []).length).toBe(1);
  });

  it('空規則 → 保留註解頭', () => {
    const out = rulesToSieve([]);
    expect(out).toContain('Generated by e2Mail');
  });
});
