import {
  SieveAction,
  SieveCondition,
  SieveRule,
} from '../types/sieve';

const uid = () => Math.random().toString(36).slice(2, 10);

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function quoteListOrOne(items: string[]): string {
  if (items.length === 1) return `"${esc(items[0])}"`;
  return `[${items.map((h) => `"${esc(h)}"`).join(',')}]`;
}

function splitList(s: string | undefined): string[] {
  if (!s) return [];
  return s
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean);
}

// ---------------------------------------------------------------------------
// 生成器：規則 → Sieve 腳本
// ---------------------------------------------------------------------------

function actionRequires(a: SieveAction, req: Set<string>) {
  if (a.type === 'fileinto') req.add('fileinto');
  if (a.type === 'fileinto' && a.copy) req.add('copy');
  if (a.type === 'reject') req.add('reject');
  if (a.type === 'setflag' || a.type === 'addflag' || a.type === 'removeflag') req.add('imap4flags');
}

function conditionTest(c: SieveCondition): string | null {
  let core = '';
  switch (c.test) {
    case 'true':
      core = 'true';
      break;
    case 'exists': {
      const headers = splitList(c.header);
      if (headers.length === 0) return null;
      core = `exists ${quoteListOrOne(headers)}`;
      break;
    }
    case 'address': {
      const headers = splitList(c.header);
      const part = c.part ? `:${c.part} ` : '';
      const hl = headers.length > 0 ? `${quoteListOrOne(headers)} ` : '';
      core = `address ${part}:${c.op} ${hl}"${esc(c.value)}"`;
      break;
    }
    case 'header':
    default: {
      const headers = splitList(c.header);
      if (headers.length === 0) return null;
      core = `header :${c.op} ${quoteListOrOne(headers)} "${esc(c.value)}"`;
      break;
    }
  }
  return c.negated ? `not ${core}` : core;
}

function actionToSieve(a: SieveAction): string | null {
  switch (a.type) {
    case 'fileinto': {
      const boxes = splitList(a.mailbox);
      if (boxes.length === 0) return null;
      return `fileinto${a.copy ? ' :copy' : ''} ${quoteListOrOne(boxes)}`;
    }
    case 'redirect':
      if (!a.address) return null;
      return `redirect "${esc(a.address)}"`;
    case 'reject':
      return `reject "${esc(a.text || 'Rejected')}"`;
    case 'discard':
      return 'discard';
    case 'keep':
      return 'keep';
    case 'stop':
      return 'stop';
    case 'setflag':
    case 'addflag':
    case 'removeflag': {
      const flags = splitList(a.flag);
      if (flags.length === 0) return null;
      return `${a.type} ${quoteListOrOne(flags)}`;
    }
    default:
      return null;
  }
}

export function rulesToSieve(rules: SieveRule[]): string {
  const enabled = rules.filter((r) => r.enabled);
  const req = new Set<string>();
  for (const r of enabled) {
    for (const a of r.actions) actionRequires(a, req);
    for (const c of r.conditions) {
      if (c.negated) {
        /* not 為核心測試，無需 require */
      }
    }
  }

  const order = ['fileinto', 'imap4flags', 'copy', 'reject'];
  const reqList = order.filter((e) => req.has(e));
  let out = '# Generated by e2Mail Sieve Rule Builder\n';
  if (reqList.length > 0) out += `require [${reqList.map((r) => `"${r}"`).join(',')}];\n`;
  out += '\n';

  if (enabled.length === 0) {
    return out + '# No rules defined\n';
  }

  for (const rule of enabled) {
    out += `# rule:[${rule.name}]\n`;
    const tests = rule.conditions.map(conditionTest);
    if (tests.some((t) => t === null)) continue;
    const realTests = tests.filter((t): t is string => !!t);
    let body = '';
    for (const a of rule.actions) {
      const s = actionToSieve(a);
      if (s === null) continue;
      body += `  ${s};\n`;
    }
    const hasTerminal = rule.actions.some((a) =>
      ['fileinto', 'redirect', 'discard', 'reject'].includes(a.type)
    );
    if (hasTerminal && !rule.actions.some((a) => a.type === 'stop')) {
      body += `  stop;\n`;
    }
    if (realTests.length === 0) {
      out += body || '  keep;\n';
      continue;
    }
    const expr =
      realTests.length === 1 ? realTests[0] : `${rule.conditionJoin} (${realTests.join(', ')})`;
    out += `if ${expr} {\n${body}}\n\n`;
  }
  return out;
}

// ---------------------------------------------------------------------------
// 解析器：Sieve 腳本 → 規則（token 化 + 遞迴下降，支援常見 Dovecot 語法）
// ---------------------------------------------------------------------------

type Tok = { k: 'quoted' | 'word' | 'annot' | 'punct' | 'num' | 'comment'; v: string };

function tokenize(src: string): Tok[] | null {
  const out: Tok[] = [];
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    if (c === '#') {
      let j = i + 1;
      while (j < n && src[j] !== '\n') j++;
      out.push({ k: 'comment', v: src.slice(i + 1, j).trim() });
      i = j;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      const e = src.indexOf('*/', i + 2);
      if (e < 0) return null;
      i = e + 2;
      continue;
    }
    if (/\s/.test(c)) {
      i++;
      continue;
    }
    if (c === '"') {
      let s = '';
      i++;
      let closed = false;
      while (i < n) {
        if (src[i] === '\\' && i + 1 < n) {
          s += src[i + 1];
          i += 2;
          continue;
        }
        if (src[i] === '"') {
          closed = true;
          i++;
          break;
        }
        s += src[i];
        i++;
      }
      if (!closed) return null;
      out.push({ k: 'quoted', v: s });
      continue;
    }
    if (c === '{') {
      const e = src.indexOf('}', i + 1);
      if (e > 0 && /^\s*\d+\+?\s*$/.test(src.slice(i + 1, e))) {
        out.push({ k: 'punct', v: '{' }); // 字面量長度（PUT 內才用；此處跳過語義）
        i = e + 1;
        continue;
      }
      out.push({ k: 'punct', v: '{' });
      i++;
      continue;
    }
    if ('}(),;['.includes(c)) {
      out.push({ k: 'punct', v: c });
      i++;
      continue;
    }
    if (c === ']') {
      out.push({ k: 'punct', v: ']' });
      i++;
      continue;
    }
    if (c === ':') {
      let j = i + 1;
      while (j < n && /[A-Za-z0-9_-]/.test(src[j])) j++;
      if (j === i + 1) return null;
      out.push({ k: 'annot', v: src.slice(i, j).toLowerCase() });
      i = j;
      continue;
    }
    const m = /^[A-Za-z_][A-Za-z0-9_-]*/.exec(src.slice(i));
    if (m) {
      out.push({ k: 'word', v: m[0].toLowerCase() });
      i += m[0].length;
      continue;
    }
    const num = /^\d+/.exec(src.slice(i));
    if (num) {
      out.push({ k: 'num', v: num[0] });
      i += num[0].length;
      continue;
    }
    return null;
  }
  return out;
}

type SimpleTest = {
  t: 'simple';
  test: 'header' | 'address' | 'exists';
  part?: string;
  op?: string;
  negated: boolean;
  headers: string[];
  values: string[];
};
type GroupTest = { t: 'all' | 'any'; children: TestNode[] };
type TrueTest = { t: 'true' };
type TestNode = SimpleTest | GroupTest | TrueTest;

class Parser {
  toks: Tok[];
  i = 0;
  error = false;

  constructor(toks: Tok[]) {
    this.toks = toks;
  }

  peek(): Tok | undefined {
    let j = this.i;
    while (j < this.toks.length && this.toks[j].k === 'comment') j++;
    return this.toks[j];
  }

  next(): Tok | undefined {
    let j = this.i;
    while (j < this.toks.length && this.toks[j].k === 'comment') j++;
    this.i = j + 1;
    return this.toks[j];
  }

  is(word: string): boolean {
    const t = this.peek();
    return !!t && t.k === 'word' && t.v === word;
  }

  expectPunct(p: string): boolean {
    const t = this.peek();
    if (t && t.k === 'punct' && t.v === p) {
      this.next();
      return true;
    }
    this.error = true;
    return false;
  }

  parseStringList(): string[] | null {
    const t = this.peek();
    if (!t) {
      this.error = true;
      return null;
    }
    if (t.k === 'quoted') {
      this.next();
      return [t.v];
    }
    if (t.k === 'punct' && t.v === '[') {
      this.next();
      const items: string[] = [];
      for (;;) {
        const it = this.peek();
        if (it?.k === 'quoted') {
          items.push(it.v);
          this.next();
        } else {
          this.error = true;
          return null;
        }
        const sep = this.peek();
        if (sep?.k === 'punct' && sep.v === ',') {
          this.next();
          continue;
        }
        if (sep?.k === 'punct' && sep.v === ']') {
          this.next();
          return items;
        }
        this.error = true;
        return null;
      }
    }
    this.error = true;
    return null;
  }

  // 回傳 {op, part, ignoreStrings}；不支援的 annotation 設 error
  parseTestAnnotations(): { op: string; part: string } | null {
    let op = '';
    let part = '';
    for (;;) {
      const t = this.peek();
      if (!t || t.k !== 'annot') break;
      this.next();
      switch (t.v) {
        case ':is':
        case ':contains':
        case ':matches':
          if (op && op !== t.v.slice(1)) {
            this.error = true;
            return null;
          }
          op = t.v.slice(1);
          break;
        case ':domain':
        case ':localpart':
        case ':user':
        case ':all':
          if (part) {
            this.error = true;
            return null;
          }
          part = t.v === ':all' ? '' : t.v.slice(1);
          break;
        case ':comparator': {
          const s = this.peek();
          if (s?.k === 'quoted') this.next();
          break;
        }
        default:
          this.error = true;
          return null;
      }
    }
    return { op: op || 'is', part };
  }

  parseTest(negDepth = 0): TestNode | null {
    const t = this.peek();
    if (!t) {
      this.error = true;
      return null;
    }
    if (t.k === 'punct' && t.v === '(') {
      this.next();
      const inner = this.parseTest(negDepth);
      if (!inner || !this.expectPunct(')')) return null;
      return inner;
    }
    if (t.k !== 'word') {
      this.error = true;
      return null;
    }
    if (t.v === 'true') {
      this.next();
      return { t: 'true' };
    }
    if (['header', 'address', 'exists'].includes(t.v)) {
      return this.parseSimpleTest(t.v as 'header' | 'address' | 'exists');
    }
    if (!['allof', 'anyof', 'not'].includes(t.v)) {
      this.error = true; // 不支援 envelope/body/currentdate/vacation 等
      return null;
    }
    this.next();
    if (t.v === 'not') {
      if (negDepth > 0) {
        this.error = true;
        return null;
      }
      const child = this.parseTest(negDepth + 1);
      if (!child || child.t !== 'simple') {
        this.error = true; // 僅支援 not + 簡單測試
        return null;
      }
      child.negated = true;
      return child;
    }
    if (!this.expectPunct('(')) return null;
    const children: TestNode[] = [];
    for (;;) {
      const child = this.parseTest(negDepth);
      if (!child) return null;
      children.push(child);
      const sep = this.peek();
      if (sep?.k === 'punct' && sep.v === ',') {
        this.next();
        continue;
      }
      break;
    }
    if (!this.expectPunct(')')) return null;
    return { t: t.v === 'allof' ? 'all' : 'any', children };
  }

  parseSimpleTest(name: 'header' | 'address' | 'exists'): TestNode | null {
    this.next(); // consume name
    const annots = this.parseTestAnnotations();
    if (!annots) return null;
    const lists: string[][] = [];
    for (;;) {
      const p = this.peek();
      if (p && (p.k === 'quoted' || (p.k === 'punct' && p.v === '['))) {
        const s = this.parseStringList();
        if (!s) return null;
        lists.push(s);
        continue;
      }
      break;
    }
    let headers: string[] = [];
    let values: string[] = [];
    if (name === 'exists') {
      if (lists.length !== 1) {
        this.error = true;
        return null;
      }
      headers = lists[0];
    } else if (name === 'header') {
      if (lists.length !== 2 || lists[0].length === 0 || lists[1].length === 0) {
        this.error = true;
        return null;
      }
      headers = lists[0];
      values = lists[1];
    } else {
      // address：1 個 list = 純 key；2 個 = [headers] key
      if (lists.length === 1) values = lists[0];
      else if (lists.length === 2) {
        headers = lists[0];
        values = lists[1];
      } else {
        this.error = true;
        return null;
      }
    }
    if (name !== 'exists' && values.length === 0) {
      this.error = true;
      return null;
    }
    return {
      t: 'simple',
      test: name,
      op: annots.op,
      part: name === 'address' ? annots.part : undefined,
      negated: false,
      headers,
      values,
    };
  }

  parseTestEntry(): TestNode | null {
    const t = this.peek();
    if (!t || t.k !== 'word') {
      this.error = true;
      return null;
    }
    return this.parseTest();
  }

  parseBlock(): { actions: SieveAction[]; nested: boolean } | null {
    if (!this.expectPunct('{')) return null;
    const actions: SieveAction[] = [];
    let nested = false;
    while (!this.error) {
      const t = this.peek();
      if (!t) return null;
      if (t.k === 'punct' && t.v === '}') {
        this.next();
        return { actions, nested };
      }
      if (t.k === 'word' && ['if', 'elsif', 'else'].includes(t.v)) {
        nested = true;
        return { actions, nested };
      }
      if (t.k !== 'word') {
        this.error = true;
        return null;
      }
      const cmd = this.parseCommand();
      if (!cmd) return null;
      if (cmd) actions.push(cmd);
    }
    return null;
  }

  parseCommand(): SieveAction | null {
    const nameTok = this.next();
    if (!nameTok || nameTok.k !== 'word') {
      this.error = true;
      return null;
    }
    const name = nameTok.v;
    const args: { annots: string[]; strs: string[] } = { annots: [], strs: [] };
    for (;;) {
      const t = this.peek();
      if (!t) {
        this.error = true;
        return null;
      }
      if (t.k === 'annot') {
        this.next();
        args.annots.push(t.v);
        continue;
      }
      if (t.k === 'quoted' || (t.k === 'punct' && t.v === '[')) {
        const s = this.parseStringList();
        if (!s) return null;
        args.strs.push(...s);
        continue;
      }
      if (t.k === 'punct' && t.v === ';') {
        this.next();
        break;
      }
      this.error = true;
      return null;
    }
    const copy = args.annots.includes(':copy');
    if (args.annots.some((a) => a !== ':copy')) {
      this.error = true;
      return null;
    }
    switch (name) {
      case 'fileinto':
        if (args.strs.length === 0) {
          this.error = true;
          return null;
        }
        return { id: uid(), type: 'fileinto', mailbox: args.strs.join(','), copy };
      case 'redirect':
        if (args.strs.length !== 1) {
          this.error = true;
          return null;
        }
        return { id: uid(), type: 'redirect', address: args.strs[0] };
      case 'reject':
      case 'ereject':
        if (args.strs.length !== 1) {
          this.error = true;
          return null;
        }
        return { id: uid(), type: 'reject', text: args.strs[0] };
      case 'discard':
        return { id: uid(), type: 'discard' };
      case 'keep':
        return { id: uid(), type: 'keep' };
      case 'stop':
        return { id: uid(), type: 'stop' };
      case 'setflag':
      case 'addflag':
      case 'removeflag': {
        if (args.strs.length === 0) {
          this.error = true;
          return null;
        }
        return { id: uid(), type: name, flag: args.strs.map((f) => f.replace(/^\\+/, '\\')).join(',') };
      }
      default:
        this.error = true;
        return null;
    }
  }

  parse(): { rules: SieveRule[] } | null {
    const rules: SieveRule[] = [];
    let lastComment = '';
    while (this.i < this.toks.length && !this.error) {
      const t = this.peek();
      if (!t) break;
      const rawAt = this.toks[this.i];
      if (rawAt.k === 'comment') {
        this.i++;
        if (rawAt.v.startsWith('rule:')) lastComment = rawAt.v;
        continue;
      }
      if (t.k === 'word' && t.v === 'require') {
        this.next();
        const strs = this.parseStringList();
        if (!strs) break;
        const semi = this.peek();
        if (semi?.k === 'punct' && semi.v === ';') this.next();
        continue;
      }
      if (t.k === 'word' && t.v === 'if') {
        const nameMatch = /rule:\s*\[?([^\]]+)\]?/i.exec(lastComment || '');
        const name = nameMatch ? nameMatch[1].trim() : `規則 ${rules.length + 1}`;
        lastComment = '';
        this.next(); // consume 'if'
        const expr = this.parseTestEntry();
        if (!expr) break;
        const blk = this.parseBlock();
        if (!blk) break;
        const after = this.peek();
        if (after?.k === 'word' && ['elsif', 'else'].includes(after.v)) {
          this.error = true;
          break;
        }
        if (blk.nested) {
          this.error = true;
          break;
        }
        const flat = flattenTest(expr);
        if (!flat) {
          this.error = true;
          break;
        }
        rules.push({
          id: uid(),
          name,
          enabled: true,
          conditionJoin: flat.join,
          conditions: flat.conds,
          actions: blk.actions,
        });
        continue;
      }
      if (t.k === 'word') {
        // 頂層裸命令 → 無條件規則
        const cmd = this.parseCommand();
        if (!cmd) break;
        rules.push({
          id: uid(),
          name: '無條件動作',
          enabled: true,
          conditionJoin: 'allof',
          conditions: [],
          actions: [cmd],
        });
        continue;
      }
      this.error = true;
    }
    if (this.error) return null;
    return { rules };
  }
}

function simpleToConditions(s: SimpleTest): SieveCondition[] {
  const base = {
    id: uid(),
    test: s.test,
    part: (s.part || '') as SieveCondition['part'],
    op: (s.op || 'is') as SieveCondition['op'],
    negated: s.negated,
    header: s.headers.join(','),
  };
  const vals = s.test === 'exists' ? [''] : s.values;
  return vals.map((v) => ({ ...base, id: uid(), value: v }));
}

function flattenTest(node: TestNode): { join: 'allof' | 'anyof'; conds: SieveCondition[] } | null {
  if (node.t === 'true') return { join: 'allof', conds: [{ id: uid(), test: 'true', part: '', op: 'is', negated: false, header: '', value: '' }] };
  if (node.t === 'simple') {
    const conds = simpleToConditions(node);
    if (conds.length > 1) return { join: 'anyof', conds };
    return { join: 'allof', conds };
  }
  const acc: SieveCondition[] = [];
  for (const child of node.children) {
    const f = flattenTest(child);
    if (!f) return null;
    if (f.conds.length > 1 && f.join === 'allof') return null; // 混層 allof 內 anyof-list 不安全
    if (node.t === 'any') {
      if (f.join === 'allof') acc.push(...f.conds);
      else if (node.children.length === 1) acc.push(...f.conds);
      else return null;
    } else {
      // allof：子節點本身必須全是 allof 條件（即單一 simple）
      if (f.conds.length !== 1) return null;
      acc.push(f.conds[0]);
    }
  }
  return { join: node.t === 'all' ? 'allof' : 'anyof', conds: acc };
}

export function sieveToRules(sieve: string): SieveRule[] | null {
  try {
    const toks = tokenize(sieve);
    if (!toks || toks.length === 0) return null;
    const p = new Parser(toks);
    const res = p.parse();
    if (!res) return null;
    if (res.rules.length === 0 && /(^|\n)\s*if\s/i.test(sieve)) return null;
    return res.rules;
  } catch {
    return null;
  }
}
