import { SieveRule } from '../types/sieve';

function escapeSieveString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function headerToSieveTest(header: string, op: string, value: string): string {
  const h = escapeSieveString(header);
  const v = escapeSieveString(value);
  switch (op) {
    case 'contains':
      return `header :contains "${h}" "${v}"`;
    case 'notcontains':
      return `not header :contains "${h}" "${v}"`;
    case 'is':
      return `header :is "${h}" "${v}"`;
    case 'notis':
      return `not header :is "${h}" "${v}"`;
    case 'matches':
      return `header :matches "${h}" "${v}"`;
    case 'exists':
      return `header :is "${h}" ""`; // fallback, Dovecot prefers exists
    default:
      return `header :contains "${h}" "${v}"`;
  }
}

function actionToSieve(a: { type: string; mailbox?: string; address?: string; text?: string }): string {
  switch (a.type) {
    case 'fileinto':
      return `fileinto "${escapeSieveString(a.mailbox || 'INBOX')}"`;
    case 'redirect':
      return `redirect "${escapeSieveString(a.address || '')}"`;
    case 'reject':
      return `reject "${escapeSieveString(a.text || 'Rejected')}"`;
    case 'discard':
      return `discard`;
    case 'keep':
      return `keep`;
    case 'stop':
      return `stop`;
    default:
      return `keep`;
  }
}

export function rulesToSieve(rules: SieveRule[]): string {
  if (rules.length === 0) {
    return `# Generated by e2mail Sieve Rule Builder\n# No rules defined\n`;
  }

  const needs = new Set<string>();
  for (const r of rules) {
    if (!r.enabled) continue;
    for (const a of r.actions) {
      if (a.type === 'fileinto') needs.add('fileinto');
      if (a.type === 'redirect') needs.add('copy');
      if (a.type === 'reject') needs.add('reject');
    }
    for (const c of r.conditions) {
      if (c.op === 'matches') needs.add('relational');
    }
  }
  // Dovecot commonly needs fileinto, copy, reject; envelope etc.
  const requireList = Array.from(needs);
  // Always need at least fileinto if any rule uses it; if empty, still include fileinto for safety
  let header = `# Generated by e2mail Sieve Rule Builder\n`;
  if (requireList.length > 0) {
    header += `require ["${requireList.join('","')}"];\n\n`;
  } else {
    header += `\n`;
  }

  let body = '';
  for (const rule of rules) {
    if (!rule.enabled) {
      body += `# Disabled: ${rule.name}\n`;
      continue;
    }
    body += `# Rule: ${rule.name}\n`;
    if (rule.conditions.length === 0) {
      // unconditional
      for (const act of rule.actions) {
        body += `${actionToSieve(act)};\n`;
      }
      body += `\n`;
      continue;
    }
    const tests = rule.conditions.map((c) => {
      // special case: exists -> header test with empty
      if (c.op === 'exists') return `exists "${escapeSieveString(c.header)}"`;
      return headerToSieveTest(c.header, c.op, c.value);
    });
    const joined = tests.length === 1 ? tests[0] : `${rule.conditionJoin} (${tests.join(', ')})`;
    body += `if ${joined} {\n`;
    for (const act of rule.actions) {
      body += `  ${actionToSieve(act)};\n`;
    }
    // auto stop after fileinto/redirect/discard/reject to avoid fallthrough; keep doesn't need stop
    const hasTerminal = rule.actions.some((a) => ['fileinto', 'redirect', 'discard', 'reject'].includes(a.type));
    if (hasTerminal && !rule.actions.some((a) => a.type === 'stop')) {
      // don't duplicate stop if already present
      body += `  stop;\n`;
    }
    body += `}\n\n`;
  }
  return header + body;
}

// 嘗試將 e2mail 生成的 sieve 反向解析為規則（僅支援自身格式）
export function sieveToRules(sieve: string): SieveRule[] | null {
  try {
    const lines = sieve.split('\n');
    // 跳過頭部 require
    const rules: SieveRule[] = [];
    let i = 0;
    while (i < lines.length) {
      const raw = lines[i].trim();
      if (raw.startsWith('# Rule:')) {
        const name = raw.replace('# Rule:', '').trim() || `Rule ${rules.length + 1}`;
        i++;
        // 期望下一行是 if ... { 或直接動作（無條件）
        const next = (lines[i] || '').trim();
        let conditions: SieveRule['conditions'] = [];
        let join: 'allof' | 'anyof' = 'allof';
        let actionStart = i;
        if (next.startsWith('if ')) {
          // 解析條件
          const condMatch = next.match(/if\s+(.+?)\s*\{$/);
          if (condMatch) {
            const expr = condMatch[1].trim();
            // 去括號
            let inner = expr;
            if (inner.startsWith('allof') || inner.startsWith('anyof')) {
              const m = inner.match(/^(allof|anyof)\s*\((.+)\)$/);
              if (m) {
                join = m[1] as 'allof' | 'anyof';
                inner = m[2];
              }
            }
            // 按逗號切（簡化，不處理引號內逗號）
            const parts = inner ? inner.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/) : [inner];
            for (const p of parts) {
              const s = p.trim();
              if (!s) continue;
              // 支援: header :contains "Subject" "value"  或  not header ...
              let m2 = s.match(/^(not\s+)?header\s+:(\w+)\s+"([^"]+)"\s+"([^"]+)"/);
              if (m2) {
                const not = !!m2[1];
                const opRaw = m2[2];
                const header = m2[3];
                const value = m2[4];
                let op = opRaw as SieveRule['conditions'][0]['op'];
                if (not && op === 'contains') op = 'notcontains';
                if (not && op === 'is') op = 'notis';
                conditions.push({ id: Math.random().toString(36).slice(2), header, op, value });
                continue;
              }
              m2 = s.match(/^exists\s+"([^"]+)"/);
              if (m2) {
                conditions.push({ id: Math.random().toString(36).slice(2), header: m2[1], op: 'exists', value: '' });
              }
            }
          }
          actionStart = i + 1;
        }
        // 收集動作直到 }
        const actions: SieveRule['actions'] = [];
        for (let j = actionStart; j < lines.length; j++) {
          const l = lines[j].trim();
          if (l === '}' || l === '}') break;
          if (l.startsWith('fileinto')) {
            const m = l.match(/fileinto\s+"([^"]+)"/);
            actions.push({ id: Math.random().toString(36).slice(2), type: 'fileinto', mailbox: m ? m[1] : 'INBOX' });
          } else if (l.startsWith('redirect')) {
            const m = l.match(/redirect\s+"([^"]+)"/);
            actions.push({ id: Math.random().toString(36).slice(2), type: 'redirect', address: m ? m[1] : '' });
          } else if (l.startsWith('reject')) {
            const m = l.match(/reject\s+"([^"]+)"/);
            actions.push({ id: Math.random().toString(36).slice(2), type: 'reject', text: m ? m[1] : '' });
          } else if (l.startsWith('discard')) {
            actions.push({ id: Math.random().toString(36).slice(2), type: 'discard' });
          } else if (l.startsWith('keep')) {
            actions.push({ id: Math.random().toString(36).slice(2), type: 'keep' });
          } else if (l.startsWith('stop')) {
            actions.push({ id: Math.random().toString(36).slice(2), type: 'stop' });
          } else if (l === '' || l.startsWith('#')) {
            continue;
          } else if (l === '}' || l.startsWith('}')) {
            break;
          }
          if (l === '}' || l.includes('}')) break;
        }
        rules.push({ id: Math.random().toString(36).slice(2), name, enabled: true, conditionJoin: join, conditions, actions });
        // 跳到 }
        while (i < lines.length && !lines[i].includes('}')) i++;
        i++;
      } else if (raw.startsWith('# Disabled:')) {
        const name = raw.replace('# Disabled:', '').trim();
        rules.push({ id: Math.random().toString(36).slice(2), name, enabled: false, conditionJoin: 'allof', conditions: [], actions: [] });
        i++;
      } else {
        i++;
      }
    }
    // 若解析結果為空但 sieve 含 if，視為非本工具生成，返回 null 讓 UI 切 Raw
    if (rules.length === 0 && sieve.includes('if ')) return null;
    return rules;
  } catch {
    return null;
  }
}
